from gym.envs.phys3d.ant import Ant
from gym.envs.phys3d.fast import Fast
from gym.envs.phys3d.fetch import Fetch
from gym.envs.phys3d.grasp import Grasp
from gym.envs.phys3d.halfcheetah import Halfcheetah
from gym.envs.phys3d.hopper import Hopper
from gym.envs.phys3d.humanoid import Humanoid
from gym.envs.phys3d.humanoid_standup import HumanoidStandup
from gym.envs.phys3d.inverted_double_pendulum import InvertedDoublePendulum
from gym.envs.phys3d.inverted_pendulum import InvertedPendulum
from gym.envs.phys3d.reacher import Reacher
from gym.envs.phys3d.reacherangle import ReacherAngle
from gym.envs.phys3d.swimmer import Swimmer
from gym.envs.phys3d.ur5e import Ur5e
from gym.envs.phys3d.walker2d import Walker2d
