from gym_gazebo.envs.modular_scara.gazebo_modular_scara_3dof import GazeboModularScara3DOFEnv
from gym_gazebo.envs.modular_scara.gazebo_modular_scara_3dof_v1 import GazeboModularScara3DOFv1Env
from gym_gazebo.envs.modular_scara.gazebo_modular_scara_3dof_v2 import GazeboModularScara3DOFv2Env
from gym_gazebo.envs.modular_scara.gazebo_modular_scara_3dof_v3 import GazeboModularScara3DOFv3Env
